Fix \q
The sequence '\q' is not tolerated by the JSON parser:
```
./src/ISA.json
Module parse failed: Unexpected token q in JSON at position 599350 while parsing near '...
                "0\qs instead of being ...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token q in JSON at position 599350 while parsing near '...
                "0\qs instead of being ...'
    at JSON.parse (<anonymous>)
```

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>